= First Anniversary!
:hp-tags: key
:published-at: 2017-12-23

Hello! scriptindex here with a special update... +

'New Letters' is now one year old! +

We have come a tough, long way. In the last year, +
a total of twenty-eight poems and one short prose piece +
have been published! That number is an incredibly great +
achievement - one that shall increase in magnitude. +

I can definitely say that having this outlet for creativity +
has been exceptionally positive for my physical, mental and +
psychological wellbeing. I hope people will continue to +
explore their creative aspirations unhinged by the influence +
of negativity, insecurities and procrastination that can +
infect us all in these most uncertain times. +

If you've read (or heard) anything I've posted - +
Thank you most kindly. The stuff I write here +
is markedly different than my usual scribblings. +
Perhaps you'd like to see more of those, hm? +

Look forward to more frequent posts, +
more experimental writing and more creative prose.

And remember - the link to
https://scriptindex.github.io[New Letters] +
is still on my Instagram
-> https://instagram.com/scriptindex[@scriptindex]

Thank you! :D