= failure
:hp-tags: poetry
:published-at: 2018-09-06

don't think about it.

---

on the twenty six years +
I've spent upon this +
magnificent Earth, +
I confess to you +
that I am +
a failure. +

across my entire life +
I have been taught things +
that were not entirely true +
about myself and countless others. +

strange behaviours +
and irrational beliefs +
treated like universal truths. +

an exercise of projection +
losing faith and direction +
in youth and adolescence +
did the sprouting begin.

it's been a cycle of frustration +
battling negative connotations +
on a wide spread speculation +
station deep in my psyche

thought I can not deny these +
very failures have resulted +
in the conscious one you see +
standing before you today +

and though I now seem to be +
everything you'd want me to be +

know that these wounds of mine +
heal in their own time, though you +
may help in your own special way

and as seconds turn into hours and my +
days become months, I want you to know +
that things will be okay +

because the world is a forgiving place, +
your struggles are not just your own +
and there are people who can help us. +

I've spent an eternity +
dragging myself out +
of those crackling thorns +
and I'm not going back +
for a very long time.

_-scriptindex, 06/09/18 thu_