= this is my life
:hp-tags: poetry
:published-at: 2018-09-04

_Wednesday 1st August 2018._

---

let me tell you about +
my personal life. +

an unwinding, declining +
strange yet confining +
sort of life. +

where routine and life and +
sleep and death are nonexistent +
in my own imagination +

where last Tuesday was +
the same as last Friday +
and no one is surprised +
because nobody cares +

a barren sphere +
where clock hands +
turn at half +
the speed +
yet my movements flow naturally +

when the thought to leave my house +
becomes the only escape where my life +
and my flow can recirculate. +

I keep telling myself +
I shall not falter, yet come the +
next day and you'll find me +
striving to see positivity +
in a comatose life such as this. +

why these hundred and thousands of +
human hands keep trying to drag me +
out but their fingers keep slipping +

they never give up but it comes down +
to me and how much I am touched by +
their countless dreams +

how I am willing to admit that +
there are people out there with +
a healing touch who bring a sliver +
of hope when I've just had enough +

and that's why +

I can't let them down, can't +
let myself down, can't let my +
mind, body and spirit down. +

Can't let the beast within take +
hold and win. Can't let those self +
restrictions keep me tightly wound. +

And I know that I can +
because others have won, +
and that's what I am +

a winner.

_-scriptindex, 04/09/18 tue_