= perspective 1
:hp-tags: poetry
:published-at: 2018-10-14

based upon the words +
of an inspiration. +

---

I'll tell you why men +
are failing with women. +

emotionally undeveloped +
men fearing rejection have +
an amplification of greater +
than average pain, seen in +
their lack of grounding, a +
disconnection giving them +
anxiety which prevents women + 
from feeling their masculinity. +

she wants to see +
how vulnerable you are +
so let your masculinity +
shine through and +
bridge that connection +

prepare for rejection +
by being rejected +
again and again +

and speak like you +
do with a friend +

because you want them +
and you wanna fuck them +
so you let them know +
your true intentions when +
you look them in the eye +
and they'll feel it inside. +

no one else will help you +
besides yourself. don't hide it +
for fear is not your friend +
so let masculinity be the key +
or there will be no attraction +

and when she's interested +
the rituals shall begin +
her games will commence +
to test your level of +
grounding and self respect. +

-

approach her. look into her eyes. +
don't bullshit. you want her and +
you want her to know that. + 

some girls aren't receptive, +
perhaps they're not in the mood +
but if you're lucky, she will +
feel a connection +

as she looks away, +
spot the signs of +
positive body language +

once she's interested enough...

pass those tests and +
watch her attraction grow. +

she wants herself to know +
you are a real man. +

she's still confirming this +
so make your move. sexually, +
discreetly. let her know +
what's up. +

confidence can only take you +
so far. it's time to put in +
the work to face your fears. +

walk the path of learning +
from your solid interactions. +

pass the shit tests. +
stand your ground. +
let her get to know you. +

approach, approach, approach +
one thousand times to get +
what you want +

and one day, you will be +
the insane fearless man +
who does not have to put +
on a show for women at all. +

how long it will take, no one +
knows, but I know what to expect +

because this is +
the hardest journey +
of my life.

_-scriptindex, 14/10/18 sun_