
= Lover
:hp-tags: poetry
:published-at: 2018-08-23

The truth is out.

---

Love is a concept quite +
dear to my melting heart. +

I am a lover of fine art +
and fine women. I take great +
care in my eloquent ways +

but the love I seek +
is not often found +

for the love I seek is +
your crown beside my throne +

and the love you seek +
is my heart within your own. +

In that delicate moment +
when you call me beside you +
and demand that you want +
me and my love tonight +

I felt I could trust you +
as I brushed your lips. +

I felt I could trust you +
when you blushed like this. +

You knew I could love you +
since I'd let you win. +

You knew I would miss you +
once I'd kissed your skin. +

Though my heart was melting, +
you held it close +
and it began to heal. +

You placed your arms around me, +
your wounds began to heal +

and as you pulled me down +
I knew life had been rough +

but you helped me forget +

as I remembered yours +

...

our palms were together +
even as you slept +

so I released my own +
to let you breathe +

your fingers sore +
from the constant digging +
your vocals hoarse from +

screaming my name +

a pleasant breath +
escapes your lips +

as I gaze upon your +
regal splendour +

and perhaps you feel +
I've seen it all +

or perhaps you feel +
I haven't seen enough +

for you rest in the presence +
of a compassionate thinker +

as you caress my cheeks +
with your right index finger +

as you reveal the truth +

that you have discovered +

"For you are my beloved +
and I am your lover." +

_-scriptindex, 23/08/18 thu_