= second perspective
:hp-tags: poetry
:published-at: 2018-12-17

based upon more words +
from an inspiration.

---

the crux of the matter +
that will make you +
understand is that +

women crave +
emotional +
validation. +

it is their version of sex, +
the equivalent to sex +
for men, perfectly. +

men fluffing Their ego +
making these girls +
feel really good +

and the girls knowing +
they've affected these men +

They will suck you +
dry then walk off. +

I chilled with this +
one girl and she tried +
to flip the dynamic +
like I'm after her +

they always fucking do it, +
addicted to validation +
like crack addicts. +

it plays into their frame +

these girls will do +
anything for validation +

just like men can do +
anything for sex. +

I just wanted to chill +
with this girl, literally +

but girls are girls +
and all they do +
is play games. +

on a surface level, +
it's an innocent request +

"Can you look after my bag? +
I'll be right back" or +
"Take a picture of me +
with my friends, please?" +

but once you do it +
they have controlled you +
and learnt they can do it +
with an innocent request +

so shit testing is +
purely to test your +
level of grounding +
and self respect. +

changing the times +
and days of dates +

they will do anything +
to see if they can +
control you +

the problem is, guys +
are completely fooled +
by surface level shit +

it's harmless right, +
no big deal +

remember, this +
dynamic is heavily +
in their favour. +

-

these days, +
my focus has shifted +

I'm improving myself +
and women are the +
by-product. +

for the record, +
I now see relationships +
as the compromise of +

man gets sex and woman +
gets emotional validation +
in the form of support +

and unfortunately, +
even the smartest chicks +
shit test subconsciously +

they are designed to. +

this is the ritual. +

you are the man they desire +

they hope you pass the tests +

shit testing commences +
when they have +
an interest. +

one more thing. +

don't let girls +
push you around. +

it's a sneaky way +
to control you +
with a smile +
on their face +

the social dynamic +
is very dominating +
in their favour +
but who ever looks +
at the dynamics. +

women want you to +
stand up to them. +

they are literally +
dying for you +
to do it. +

so the best teacher +
is experience +

get the basic knowledge +
then use it to reflect +
on actual incidents. +

my body language, +
my tonality, my eyes, +
my facial expressions +
convey WAY too much +
interest. +

for me, personally +
it's really effective +
to display disinterest +

it creates a need inside +
a woman for validation +

you'd be surprised how +
many guys have programmed +
themselves to behave in a way +
that constantly conveys +
too much interest +

all the time, and +
they're not even aware. +

you think what you say matters +
when your body is showing +
your true hand.

_-scriptindex, 17/12/18_