= Revelation.
:hp-tags: poetry
:published-at: 2018-09-29

the truth will set you free.

---

"Tell me, Oracle of the Night. +
Why have you brought me +
to yourself tonight?" +

Through your palace doors +
and marble steps to the +
sanctuary of your Throne. +

I felt safe in the knowledge +
you could do me no wrong. +

In your presence +
I could only watch +
as your faint blue aura +
was revealed to me. +

Perhaps you knew +
my limitations +

for my poetry is a mask +
of intense realisation, +
one I laid at your feet +
for you to communicate +
your thoughts to me. +

within my mind, an +
eternity had passed as +
I awaited the wisdom +
only you could bring +

and as you walked away, +
untouched by the softness +
of a human heart, I knew +
the time had not yet come +

yet as I raised the mask +
to my face, I felt faint +
trickles down my fingertips +

simply teardrops +

never to be seen again. +

Thank you, +
Oracle of Tonight. +

Thank you +
for reviving my +
world of possibility. +

Our paths will cross again +
someday. I can feel it +
in the blood that flows +
through my veins +

for it would be a shame +
to live this life +
without your presence +

in my sunset +
sunrise afterlife. +

It would truly be +
an unfortunate oversight +

in the life of +
an Oracle in Flight. +

It would only be +
between you and me +

only you and me. +

farewell +
my beloved. +

may we meet again +

someday.

_-scriptindex, 29/09/18 sat_