= Women.
:hp-tags: poetry
:published-at: 2018-09-11
 
just for you.
 
---
 
I have never had +
much success +
with women +
 
though I've been +
constantly searching +
like an intoxicated rat +
 
to get my fix, +
my dopamine delight +
running back and forth +
like I'm on cloud nine, +
steering clear of the +
traps and obstacles +
in my way +
 
but once it wears off +
I am alone again +
lying in my bed +
lying to myself +
eyes facing the wall +
looking dead inside +
 
it's not the first time +
because it's every time +
 
days and months and years +
of pure confusion, damn jealousy, +
unfiltered guilt and basically +
one hundred thousand moments +
spent not in your eyes, but a waste +
of time as I struggled to understand +
why, why, why am I still alive? +
 
how did I never contemplate why +
these girls and women were more +
like lessons for a class I'd always +
been skipping. how they've all been +
my muse in one way or another +
as spring turned summer +
and autumn turned winter +
 
but I've had enough lessons +
and I've got enough muses. +
 
When will a real woman +
come to show me the way? +
 
When will I learn what a +
real relationship should be? +
 
before that moment +
I've got some things to do +
for it seems to me that +
I have the key, and the +
lock is within me. +
 
I ask myself what a woman +
means to me. I ask again what +
I want in a woman. I ask about +
my boundaries, your boundaries, +
matching compatibility with +
capability, creative energy, +
independent identity +
 
things I can not compromise. +
 
I need more than just a pretty face. +
I want more than just your gallery. +
I need details, more details, +
I want to get to know you. +
 
it's a tricky situation +
and I'd best not fall +
back into those ways +
when I lost myself +
in the pursuit of others +
 
so I've got a lot of time +
before I have to rush back +
cause it's just my luck +
and you wanna +
know why? +
 
they keep on getting younger, +
I keep getting older +
 
and I'm just getting +
too old for this.

_-scriptindex, 11/09/18 tue_