= deadline
:hp-tags: poetry
:published-at: 2018-07-24

constant ticking.

---

"The deadline is tonight. +

What has been said +
must be done in full. +

There will be +
no compromises."

Hearing these words +
in the depths of my mind +
I take my last step +
leaving my heavy heart +
and my woes behind +

Sometimes you wonder +
what lies on the other side. +
Sometimes you wonder +
if that is where you belong. +

every minute or so +
a crawling sensation +
spreads to my neck +
and grasps real tight +
a reckless bull caught +
within the snares of +
a persistent cowboy +
with one too many +
pegs to throw +

It will continue +
for however long +
I allow it, however +
I am not the one +
they think I am. +

that time is not far +
when reward shall +
outweigh loss. +

I bring peace in folds +
of paper, containing +
words of sustenance, +
of hope. +

The time has now come +
when thought becomes +
action. +

wish me luck +
good friends of mine +
for the true challenge +
begins now.

_-scriptindex, 24/07/18 tue_