= Third Anniversary!
:hp-tags: key
:published-at: [2019-12-23]

Hello there. scriptindex here with a special update... +

'New Letters' is finally three years old! +

There are now 78 'poetry' pieces and one 'prose' piece. +
Perhaps I should write some prose sometime... +

This year's offerings have been fewer in number +
though I believe you can really see the difference +
in quality when compared to previous pieces or +
simply as their own individual poems. +

It's been an interesting year. I've been quite relaxed +
with poetry events and I'm writing more often in the +
meanwhile. To keep that creative muscle working as +
much as possible - that is the most important thing. +

I've been posting a lot more on Instagram lately +
and I'm sure you've been reading it quite often, +
but now I have something else to say... +

It's time for an indefinite social media break. +

I need some time off. I want to think about things. +
I want to be alone for a while. I will be back. +

'New Letters' is where I will post my creative pieces +
in the meanwhile. It's good to be back on this website +
and I'm looking forward to writing some new poems. +

It would be useful to bookmark this page and check back +
every now and then for new poems. My Twitter posts do link +
back here so if you use it regularly, you're in good hands. +

The hyperlink to 
https://scriptindex.github.io[New Letters] is always +
on my Instagram page 
-> https://instagram.com/scriptindex[@scriptindex]

Don't forget about 
https://twitter.com/scriptindex2[Twitter]! +

See you next time.