
= CREATE NEW POST ON 23/11 oyl
:hp-tags: poetry
:published-at: 2019-11-21 NEW POST -23

Before we begin, +
I would like to state the following: +

[This poem has been on my mind for the past year. +
If the matter was resolved, it would not exist. +
I have to stand up for myself, because no one else +
can, or will. In that sense, I have no regrets.] +

This is the longest piece I have ever written. +
It's quite conversational so you will enjoy it. +

It is best experienced by reading through the +
entire thing, then checking all of the hyperlinks. +

So, you're finally ready. Let us begin. +

---

Friday 23rd November 2018. +

I was heading to the +
Rich Mix in Shoreditch +

to enjoy an evening of +
spoken word and music +



"reimagi[ing] masculinity +
through a queer and feminist lens" +

a collaboration between the South Asian +
collective, https://www.instagram.com/theyoniversecollective[The Yoniverse] and 

https://richmix.org.uk/events/the-yoniverse-x-leo-kalyan-present-the-edge/[THE YONIVERSE X LEO KALYAN PRESENT: THE EDGE]

tonight, masculinity would be +
"reimagined...through a queer +
and feminist lens" +


five slots on the day, +
with priority given to +


and also +
perform a https://scriptindex.github.io/2018/09/11/Women.html[spoken word piece] +
I had https://farm66.static.flickr.com/65535/48596076557_f842c1df74.jpg[memorised] not long ago +
for a recent https://www.youtube.com/watch?v=LWjxVYxxkGE[poetry event]. +

Looking at these https://www.facebook.com/pg/theyoniversecollective/photos/?tab=album&album_id=298107960823996[lovely photos], +
it looks like everything went well.

there's a https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298108187490640/?type=3&theater[few] pictures of https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298109637490495/?type=3&theate[me] +
performing on that https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298110540823738/?type=3&theater[stage] +

and everyone +


What if I told you +
things didn't go +
as well 

What if I told you +
the truth lies

F




there was this one +
brown girl. her energy +
was a bit strange +

she looked like +
the kind of girl +
that would get +
angry at anything +









then I https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298111290823663/?type=3&theater[came back] +
to finish the piece +




And it's unfortunate +
since I was ready to +
recommend the event to +
all of my poetry friends. +

oh well. at least +
https://www.instagram.com/p/Bqm0lwunQ9A/[the buns] were nice.






if I don't know what +
I did "wrong" then how +
am I expected to improve, +
to prevent myself from +
doing the exact thing again +


as far as I am aware, +
https://twitter.com/DimplePau/status/1066100076949450752[this twitter post] is the +
only reference I have found +

yes, it is about me +
and no, I have no clue +
what she's talking about. +

F


the

Please bear in mind that she +
offered to meet up only after +
I had approached her myself and +
expressed my desire to discover +

why the piece was received +
in that way. I doubt she +
would have otherwise. +

So I took up her offer and +
messaged her directly the +
next day over Instagram and +
she was quite cooperative +

though we were unable to meet, +
Shagufta stated she would +
"send [me] some dates and see +
if we can meet before Xmas." +

Sounds great. I replied back +
and sent another two messages. +

Let's see what happened. +

Nov 28, 9:02pm: Seen. +
Dec 17, 5:03pm: Seen. +
>Jan 7, 9:05pm: Seen. +

It is pretty clear that we +
were not going to meet up. +

At this point, I knew that +
I was not going to find any +
answers. Not that she was +
obliged to explain anything +

to me. Realising this truth, + 
I decided to leave it at that. +

-

However, as I was writing this +
incredibly long piece, I noticed +
that The Yoniverse has scrubbed +
nearly all mention of the event +

on their Instagram page. I recall +
a post with some Facebook pictures, +
their open mic policy post - both gone. +

Just thought I'd mention that. +

-

When situations aren't +
resolved, you receive +

no closure, no idea of +
what went wrong or +
how you can improve +

it can damage you +
in ways you may +
not realise. +

Fortunately, I had +
two other creative +
events that weekend +

where I wanted +
to perform 'Women.' +

so I didn't have time +
to rest in my sorrow +

but just to be sure +

I double checked +
with the founder of +
Saturday's event: +

"I've performed it a +
few times but last night +
it was quite divisive +
among Feminists..." +

She responded with a +
video message saying +
that "Poetry is about +
expressing yourself." +

she enjoyed the piece, +
by the way. +

I didn't get the time +

to perform it, but it +
was okay since I was +

preparing


It was at that point +
where I realised that +
it was not the piece +
that was offensive +

rather, it was the +
audience that found +
the piece offensive. +

-

Looking back +
I realise that +
from 18/11 to 23/12, +
 
I didn't post
anything on my +
Instagram page +

I was still +


upcoming events but +


reaching a new arc +
in my creative career +




I had already written +
the sensitive 

https://scriptindex.github.io/2018/10/14/perspective-1.html['Perspective 1']

TK

thanks to my ability +
to 


is the very reason +
I was confident enough +

to write and perform +
the spectacular sensation, +
https://scriptindex.github.io/2018/12/17/second-perspective.html['second perspective'] +

Not my words, by the way +
but if you've reached this +
far and haven't exploded +
with rage, keep reading... +

-

I've given you all +
the information you +
require to understand +

why this event holds +
so much importance +
for me, but if you +

really want to know +
why I wrote the poem +

the one you are +
reading right now +

there is a very +
simple answer. +

-

This is a story +
that deserves +
to be told. +

The story you +
deserve to know. +

It will not be +
invalidated or +
silenced +

suppressed, +
or distorted +

by anyone +
or everyone. +

May it be a lesson +
to those who think +
otherwise. +

-

To conclude, I would like +
to personally deliver this +
handwritten letter to its +
rightful recipient... +

...

To the Yoniverse, +

It is Saturday 23rd November 2019. +

It has been exactly one year +
since I came on your stage +
to recite my poetry. +

three hundred and +
sixty five days later +

I hope this is the +
learning experience +
you were looking for. +

The Yoniverse, +

It seems you underestimated +
what one South Asian man +
is capable of. +

I hope you will not make +
the same mistake twice. +

I do not expect your +
forgiveness, for the +
time has long gone +

I know you will +
not forget this +

but it doesn't +
matter anymore, +

because... +

it's over +

there is nothing +
left to say +

so I shall leave you +
with the very words +

I said to your founder +
on that fateful evening: +

"I hope I don't take up +
too much time in your +
red book meeting." +

Yours truly, +
https://www.instagram.com/scriptindex/[scriptindex]

_-scriptindex, 23/11/19 sat_