
= CREATE NEW POST ON 23/11 oyl
:hp-tags: poetry
:published-at: 2019-11-21 NEW POST -23

Before we begin, +
I would like to state the following: +

[This poem has been on my mind for the past year. +
If the matter was resolved, it would not exist. +
I have to stand up for myself, because no one else +
can, or will. In that sense, I have no regrets.] +

This is the longest piece I have ever written. +
It's quite conversational so you will enjoy it. +

It is best experienced by reading through the +
entire thing, then checking all of the hyperlinks. +

So, you're finally ready. Let us begin. +

---

Friday 23rd November 2018. +

I was heading to the +
Rich Mix in Shoreditch +

to enjoy an evening of +
spoken word and music +

and perform a very +
personal poetry piece. +

This collaboration between +
the South Asian female +
poetry collective, +

https://www.instagram.com/theyoniversecollective[The Yoniverse] and singer-songwriter +
https://www.instagram.com/leokalyan[Leo Kalyan] would "reimagine masculinity +
through a queer and feminist lens" +

in the appropriately titled: +

https://richmix.org.uk/events/the-yoniverse-x-leo-kalyan-present-the-edge/[THE YONIVERSE X LEO KALYAN PRESENT: THE EDGE]

Looking at these https://www.facebook.com/pg/theyoniversecollective/photos/?tab=album&album_id=298107960823996[lovely photos], +
it looks like everything went well.

there's a https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298108187490640/?type=3&theater[few] pictures of https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298109637490495/?type=3&theate[me] +
performing on that https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298110540823738/?type=3&theater[stage], +

some https://www.instagram.com/p/Bqm0lwunQ9A/[nice buns] and +
lots of https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298110407490418/?type=3&theater[happy smiles]. +

-

but this is not +
the full story. +

what if I told you +

there is an +
untold story +

suppressed from +
the public eye +

that no one +
will ever know? +

-

the time has come +
to reveal all. +

this is the real +
'learning experience'. +

tonight, you will +
learn many things, +

including... +

the incident itself, +
my search for the truth, +
the response I received, +
how it has affected me, +
why this piece exists +
and my final thoughts +
to The Yoniverse. +

I have tried my best +
to tell you how it went. +

There may be some +
discrepancy in terms +
of the ordering, but +

I have tried my best +
to be honest with you. +

I hope you can trust me. +

-

Friday 23rd November 2018. +

I wanted to perform +
a https://scriptindex.github.io/2018/09/11/Women.html[spoken word] piece +
I had https://farm66.static.flickr.com/65535/48596076557_f842c1df74.jpg[memorised] for +
a recent https://www.youtube.com/watch?v=LWjxVYxxkGE[poetry event]. +

the title: +

'Women.' +

I had two things to consider. +

Firstly, there were +
only five open mic +
slots on the day. +

Secondly, I saw an +
Instagram post about +
their unique open mic +
policy (now removed) +

giving priority to +
to South Asian https://feministoasis.com/inclusive-language-womxn-cis-nonbinary[womxn] +
and queerfolk. +

I had never seen a policy +
like this before, so I was +
sure to get there early. +

it was the only thing +
I could really do +

to maximise my chances +
of performing there.

-

on the night, I saw +
the following members +
of The Yoniverse: +

https://www.instagram.com/shaguftakiqbalpoet[Shagufta K Iqbal], +
https://www.instagram.com/shareefaenergy[Shareefa Energy], +
https://www.instagram.com/amanithepoet[Amani Saeed]. +

https://www.instagram.com/salmaelwardany[Salma El-Wardany] was +
also https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298111400823652/?type=3&theater[there] but I didn't +
see her on the night. +

As I asked around, +

I realised that +
Amani was signing +
up the open micers +

so I went up to her +
and she wrote my +
name down. +

-

The event itself was +
actually pretty good. 

https://www.instagram.com/leokalyan[Leo Kalyan] discussed +
his creative process +

and beautifully sang +
his latest EP: https://www.youtube.com/watch?v=s4KcLu9CNdo[the edge], +

https://www.instagram.com/shareefaenergy[Shareefa Energy] carefully +
recited her soul-soothing, +
tongue-twisting poetry +

and https://www.instagram.com/raheemmir[Raheem Mir] performed +
some barrier-breaking, +
gender-bending https://kathadance.org/about-2/what-is-kathak/[Kathak]. +

I thoroughly enjoyed +
myself and was looking +
forward to coming +

the next time.

-

It was time. +

My name was called. +

The time had come +
to perform the piece +
I had memorised +
off by heart. +

https://scriptindex.github.io/2018/09/11/Women.html['Women.'] +

-

things were alright +
at the beginning +

but as the piece +
drew to a close +

I noticed something +
was happening. +

there was +

a growing +
commotion +
of sorts. +

I could hear +

Shagufta, who +
was talking to +
someone near her. +

"...this can't go on..." +

it took a few seconds +

but when I realised +

"it's a tricky +
situation, and-" +

I stopped. +

pure silence. +

-

there was this one +
brown girl. the one +
with the colourful +

jacket. her energy +
was a bit strange +
that evening +

she seemed like +
she was angry +
in general, and +

she expressed her +
distaste quite +
vocally when +

she shouted: +

"Women are not your playthings!" +

what? +

to this day, +
I have no clue +
what she meant +

but that was just +
the start. +

there was also +
this white girl +

standing behind a table +
at the back of the room. +

I don't know who she is +

but she knows who she is. +

she was very +
offended by +

something +
I had said. +

she also chose +
to be vocal. +

-

I don't remember +
the exact words +

but Amani walked +
towards me, saying +

they didn't know +
it was "that +
kind of piece" +

so she asked me +
to give back the mic. +

-

in my entire career +
as a spoken word artist +

that was the first time +
I had been asked to +
give back the mic. +

when you don't +
know why, well, +

I'm sure you can +
imagine how it feels... +

-

Shagufta said they +
(as in, the team) +
were waiting +

to see if the +
piece would +
change +

and it didn't. +

I wondered how +
things had come +
to this. +

why I decided +
to perform +
that piece. +

why I came +
to this event. +

just why. +

-

right before +
I was about +
to give the +
mic back

I took the +
opportunity +
to say that +

I was sorry +

if I hurt +
anyone's +
feelings. +

in retrospect, +

I should never +
have said sorry. +

it's pretty simple. +

when you offend someone, +
especially liberals, +

your apology +
is meaningless. +

it's damage control +
in their eyes. +

they want more +
that just an +
apology... +

they want +
your blood, +
your career, +
your social +
standing, +
your life. +

they will do +
whatever they can +
to destroy you. +

I had read about +
this countless +
times, but this +

was the first time +
I understood it +

and I vowed to learn +
from that experience +

so it wouldn't +
happen again. +

-

there is one +
silver lining +
to this drama. +



Cheers Leo. +


about how it's


Cheers, Leo. +

-

there was one +
last person on +
the open mic +

so once he +
had finished, +

it was decided +
that there would +
be a discussion +

of some kind +

about what +
just happened +

-

now that I had +
derailed the +
entire evening +

there was a +




as I said earlier, +
https://www.instagram.com/salmaelwardany[Salma] was present. +

the voice sounded +
similar and I think +
she's the one who, +

when asked for her +
thoughts, said +
"I hate men..." +

but that was quite +
dehumanizing and +
could have been +
handled better. +

-

at some point, +

white girl decided +
she was not satisfied. +

she could not comprehend +
what I had just done +

so she asked Leo and +
Amani if she could ask +
me a question. +

I think she asked me +
why I wrote the piece +
or what I was thinking +
when I wrote it. +

can you imagine, +

having literally +
everyone in the +
entire room +

roughly seventy +
five people or so +

turning to look +
directly at you +

expecting a response +

while you are still +
in a state of shock? +

I don't even want +
to think about it. +

fortunately, I was +
still somewhat sane +
at that point +

saying something about +
my personal experience +
and how I'm still in a +

state of shock right now 
so I can't think properly. +

all I would like +
to say, is +

thanks for that, +
white girl. +

no, really. +

I hope I never see you +
again in my entire life. +

-

as far as I'm aware, +
https://twitter.com/DimplePau/status/1066100076949450752[this twitter post] is the +
only reference I have. +

she called it a +
"passionate discussion +
on free speech." +

'learning experience'. +

it's the same thing. +

-

F


me coming back +
to finish the piece +

on the basis that +




-

at this point, 

by public outcry, +
the Y

I remember Amani 



I was really +
not feeling it +

and I gave her +

the most emotionally +
devoid look I have +

ever given to anyone +
in my entire life. +

it's a good thing +
they asked more +
than once. +

you see, +
I was asked again +
sometime later +

and by that time, +
I realised that +

if I finished +
off the piece, +

it would not only +
confirm or deny +
people's opinions +
about 'Women.', +

but also +
remove the +

sense of +
mystery +

you know, like +

will we ever +
know the truth +
kinda mystery +

however, +

due to overwhelming +
popular demand and +

my desire to set +
the record straight +

I https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298111290823663/?type=3&theater[came back] on stage +

to finish the piece. +

-

the crowd was +
more tolerant +
at this point. +

some womxn +
even smiled +

but now, +

I was about to +
https://scriptindex.github.io/2018/09/11/Women.html["open Pandora's box"] +
with every word. +

after a few seconds, +

the piece began, +

it was happening +

then it finished, +

and I stopped +

to look around +

at the entire room. +

-

there was more talk of +
a 'learning experience' +

some other stuff +
I can't remember +

the show ended +
at some point, +

as all shows do +

and I wondered what +
would happen next. +

I had some questions on +
my mind. Things I wanted +
to know and understand. +

I did not know +
what I did 'wrong'. +

I was not sure +
how to prevent this +
from happening again, +

or how to learn +
from this experience. +

hopefully someone +
had the answers I +
was looking for. +

-

as I stood up +
from my seat +

I talked to the +
womxn next to me, +

who said two things. +

she thanked me for +
finishing the piece +

then looked me +
in the eye +

with a sad face, +

saying that +
whatever happened... +

"that wasn't right." +

I had a few people +
come up to me +
right after that.

whether they were +
virtue signalling or +
not, I wasn't overly +

concerned, but I did +
get some thanks for +
finishing the piece. +

a short while later, +

two womxn came up to me, +
basically saying that +

it wasn't right how I was +
treated and that it should +
have been handled better.

they were confused about +
the whole thing themselves, +

thanked me for +
finishing the piece +

and suggested I check +
the wording of the poem +

as there may have been +
something there which +
had offended people. +

-

you may find this +
quite interesting. +

I recall one womxn +
I had a brief chat +
with. she wanted +

to talk to me +

but she seemed +
apprehensive about +
being seen with me +

or seen talking to me. +

during our chat, +
she referenced +

the reason for +
her behavior in +
a joking manner +

but I knew what +
she meant. +

there is no +
mistaking that +
energy. +

she knew what +
could happen, +

but she still +
came up to me. +

thank you for +
talking to me. +

-

on my way out, +
The Yoniverse team +
was packing up. +

seeing an opportunity, +

I went up to Amani, +
Shareefa and Shagufta +

very briefly to say the +
same thing to all of them +

that I wasn't sure why the +
piece was taken in that way, +

while hoping they had +
some kind of answer. +

Amani and Shareefa chose +
silence over response, +
but Shagufta responded... +

I'm paraphrasing a bit here +
but she basically said: +

"I can tell you what's wrong with +
it, but..." right now it's quite +
overwhelming so not right now +
but we can meet up over coffee +
and discuss this. +

Please bear in mind that she +
offered to meet up only after +

I had approached her myself and +
expressed my desire to discover +

why the piece was received +
in that way. I doubt she +
would have otherwise and +

I'm sure she would rather +
I walked out, hoping she would +
never see or talk to me ever again. +

-

So I took up her offer and +
messaged her directly the +
next day over Instagram and +
she was quite cooperative +

though we were unable to meet, +
Shagufta stated she would +
"send [me] some dates and see +
if we can meet before Xmas." +

Sounds great. I replied back +
and sent another two messages. +

Let's see what happened. +

Nov 28, 9:02pm: Seen. +
Dec 17, 5:03pm: Seen. +
>Jan 7, 9:05pm: Seen. +

It is pretty clear that we +
were not going to meet up. +

At this point, I knew that +
I was not going to find any +
answers. Not that she was +
obliged to explain anything +

to me. Realising this truth, + 
I decided to leave it at that. +

-

when situations aren't +
resolved, you receive +

no closure, no idea of +
what went wrong or +
how you can improve +

it can damage you +
in ways you may +
not realise. +

Fortunately, I had +
two other creative +
events that weekend +

where I wanted +
to perform 'Women.' +

so I didn't have time +
to rest in my sorrow +

but just to be sure +

I double checked +
with the founder of +
Saturday's event: +

"I've performed it a +
few times but last night +
it was quite divisive +
among Feminists..." +

She responded with a +
video message saying +
that "Poetry is about +
expressing yourself." +

she enjoyed the +
piece, by the way. +

I didn't perform it due +
to lack of time, but it +
was fine since I had +

Sunday evening +
to power through +

so I checked up +
with the founder +
and all he said was... +

"Looks good!" +

Before my performance, +
I gave the audience +
a rough account of +

what happened that +
Friday evening +

and it was tough +
but I got through +
the entire piece. +

there was a positive +
response from everyone +

I talked to, yet they also +
shared the same confusion +
that I had experienced +

and no one could +
pinpoint why that +
poem in particular +
was found offensive. +

as we waited for the bus, +

I opened up to a few +
of my poetry buddies +
about the situation. +

we talked and talked, +
talked and talked +
and eventually, +

there was a point +
where I realised that +

it was not the piece +
that was offensive +

rather, it was the +
audience that found +
the piece offensive. +

it sounds pretty obvious +

and it is, but if people +
were offended, so what? +

to be offended is a choice. +

perhaps at some level, +
I was trying to convince myself +
that it wasn't them, but me. +

not this time, +
womxn. +

now I realise +

it's not me, +

it's you. +

-

From 18/11 to 23/12, +
 
I didn't post +
anything on my +
Instagram wall. +

I was still 'promoting' +
creative events through my +
Stories, as I usually did +

but I recall reading my notes +
for 'Second Perspective' +
and feeling incredibly fired up. +

Due to its subject matter, +
I had been putting it off +

since I wasn't sure if +
I could perform it +

without being shut down +
by the opposite sex +

but during that month +
of no new poetry, +

it was like an obsession +
had taken hold. no longer +
was procrastinating an option. +

success was and would +
be the only option. +

I had already written +
the sensitive showstopper, +
https://scriptindex.github.io/2018/10/14/perspective-1.html['Perspective 1'] +

but it is only once +
I had performed it +

that a new truth +
was revealed to me: +

I was reaching a new arc +
in my creative career. +

If you were there +

on Thursday 20th December 2018 +

for the first and +
only performance +

of the spectacular sensation, +
https://scriptindex.github.io/2018/12/17/second-perspective.html['second perspective'] +

I actually forgot to mention +
those words were not mine +

that I had applied +
my creative touch +
with great precision +

so if you've reached this +
far and haven't exploded +
with rage, keep reading... +

I'm not done yet. +

-

I've given you all +
the information you +
require to understand +

why this event holds +
so much importance +
for me, but if you +

really want to know +
why I wrote the poem +

the one you are +
reading right now, +

there is a very +
simple answer +

-

This is a story +
that deserves +
to be told. +

The story you +
deserve to know. +

It will not be +
invalidated or +
silenced +

suppressed, +
or distorted +

by anyone +
or everyone. +

May it be a lesson +
to those who think +
otherwise. +

-

To conclude, I would like +
to personally deliver this +
handwritten letter to its +
rightful recipient... +

...

To the Yoniverse, +

It is Saturday 23rd November 2019. +

It has been exactly one year +
since I came on your stage +
to recite my poetry. +

three hundred and +
sixty five days later +

I hope this is the +
learning experience +
you were looking for. +

The Yoniverse, +

It seems you underestimated +
what one South Asian man +
is capable of. +

I hope you will not make +
the same mistake twice. +

I do not expect a +
response, for the +
time has long gone. +

I know you will +
not forget this +

but it doesn't +
matter anymore, +

because... +

there is nothing +
left to say +

it's over +

so I shall leave you +
with the very words +

I said to your founder +
on that fateful evening: +

"I hope I don't take up +
too much time in your +
red book meeting." +

Yours truly, +
https://www.instagram.com/scriptindex/[scriptindex]

_-scriptindex, 23/11/19 sat_