= one year later 2
:hp-tags: poetry
:published-at: 2019-11-23

https://scriptindex.github.io/2019/11/23/one-year-later.html[(read part one)] +
before you continue. +

---

I remember https://www.instagram.com/amanithepoet[Amani] +
standing there +
on that stage +

asking me if +
I wanted to +

come back on stage +
to finish the piece. +

I was really +
not feeling it +

and I gave her +

the most emotionally +
devoid look I have +

ever given anyone +
in my entire life. +

it's a good thing +

she decided to +
ask me again +

a bit later +

when I was +
feeling a +
bit better +

and by that time, +
I realised that +

if I finished +
off the piece, +

it would not only +
confirm or deny +
people's opinions +
about https://scriptindex.github.io/2018/09/11/Women.html['Women.'], +

but also +
remove the +

sense of +
mystery +

you know, like +

will we ever +
know the truth +
kinda mystery +

however, +

due to overwhelming +
public demand and +

my desire to set +
the record straight +

I https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298111290823663/?type=3&theater[came back] on stage +

to finish the piece. +

-

the crowd was +
more tolerant +
at this point. +

some womxn +
even smiled +

but now, +

I was about to +
https://scriptindex.github.io/2018/09/11/Women.html["open Pandora's box"] +
with every word. +

after a few seconds, +

the piece began, +

it was happening +

then it finished, +

and I stopped +

to look around +

at the entire room. +

-

there was more talk of +
a "learning experience" +

and some other +
stuff I can't +

remember. +

the show ended +
at some point, +

as all shows do +

and I wondered what +
would happen next. +

I had some questions on +
my mind. Things I wanted +
to know and understand. +

I did not know +
what I did 'wrong'. +

I was not sure +
how to prevent this +
from happening again, +

or how to learn +
from this experience. +

hopefully someone +
had the answers I +
was looking for. +

-

as I stood up +
from my seat, +

I talked to a +
womxn beside me +

who said two things. +

she thanked me for +
finishing the piece +

then looked me +
in the eye +

with a sad face, +

saying that +
whatever happened... +

"that wasn't right." +

I had a few people +
come up to me +
right after that.

whether they were +
virtue signalling or +
not, I wasn't overly +

concerned, but I did +
get some thanks for +
finishing the piece. +

a short while later, +

two womxn came up to me, +
basically saying that +

it wasn't right how I was +
treated and that it should +
have been handled better.

they were confused about +
the whole thing themselves, +

thanked me for +
finishing the piece +

and suggested I check +
the wording of the poem +

as there may have been +
something there which +

had offended people. +

-

you may find this +
quite interesting. +

I recall one womxn +
I had a brief chat +
with. she wanted +

to talk to me +

but she seemed +
apprehensive about +
being seen with me +

or seen talking to me. +

during our chat, +
she referenced +

the reason for +
her behavior in +
a joking manner +

but I knew +
what she meant. +

there is no +
mistaking that +
energy. +

she knew what +
could happen, +

but she still +
came up to me. +

Thank you for +
talking to me. +

-

on my way out, +
https://www.instagram.com/theyoniversecollective[The Yoniverse] team +
were packing up. +

seeing an opportunity, +

I went up to https://www.instagram.com/amanithepoet[Amani], +
https://www.instagram.com/shareefaenergy[Shareefa] and https://www.instagram.com/shaguftakiqbalpoet[Shagufta] +

very briefly to say the +
same thing to all of them +

that I wasn't sure why the +
piece was taken in that way +

while hoping they had +
some kind of answer. +

Amani and Shareefa chose +
silence over response, +
but Shagufta responded... +

I'm paraphrasing here +
but she basically said: +

"I can tell you what's wrong with +
it, but..." right now it's quite +
overwhelming so not right now +
but we can meet up over coffee +
and discuss this. +

Please bear in mind that she +
offered to meet up only after +

I had approached her myself and +
expressed my desire to discover +

why the piece was received +
in that way. I doubt she +
would have otherwise and +

I'm sure she would rather +
I walked out, hoping she would +
never see or talk to me ever again. +

then again, I did +
derail her event... +

-

So I took up her offer and +
messaged her directly the +

next day over Instagram and +
she was quite cooperative. +

though we were unable to meet, +
Shagufta stated she would +
"send [me] some dates and see +
if we can meet before Xmas." +

Sounds great. I replied back +
and sent another two messages. +

Let's see what happened. +

Nov 28, 9:20pm: Seen. +
Dec 17, 5:03pm: Seen. +
>Jan 7, 9:05pm: Seen. +

It is pretty clear that we +
were not going to meet up. +

At this point, I knew that +
I was not going to find any +
answers. Not that she was +
obliged to explain anything +

to me. Realising this truth, +
I decided to leave it at that. +

-

when situations aren't +
resolved, you receive +

no closure, no idea of +
what went wrong or +
how you can improve +

it can damage you +
in ways you may +
not realise. +

Fortunately, I had +
two other creative +
events that weekend +

where I wanted +
to perform https://scriptindex.github.io/2018/09/11/Women.html['Women.'] +

so I didn't have time +
to rest in my sorrow +

but just to be sure +

I double checked +

with the founder of +
Saturday's event: +

"I've performed it a +
few times but last night +

it was quite divisive +
among Feminists..." +

She responded with a +
video message saying +
that "Poetry is about +

expressing yourself." +

and yes, she +
enjoyed the piece. +

I didn't perform it due +
to lack of time, but it +
was fine since I had +

Sunday evening +
to power through +

so I checked up +

with the founder +
of Sunday's event +

and all he said was... +

"Looks good!" +

-

Before my performance, +
I gave the audience +
a rough account of +

what happened that +
Friday evening +

and it was tough +

but I got through +
the entire piece. +

there was a positive +
response from everyone +

I talked to, yet they also +
shared the same confusion +
that I had experienced +

and no one could +
pinpoint why that +
poem in particular +

was found offensive. +

as we waited for the bus, +

I opened up to a few +
of my poetry buddies +
about the situation. +

we talked and talked, +
and talked, until... +

there was a point +
where I realised that +

it was not the piece +
that was offensive +

rather, it was the +
audience that found +
the piece offensive. +

it sounds pretty obvious +

and it is, but if people +
were offended, so what? +

to be offended is a choice. +

perhaps at some level, +
I was trying to convince +

myself that it +
wasn't them, +
but me. +

not this time, +
womxn. +

now I realise +

it's not me, +

it's you. +

-

From 18/11 to 23/12, +

I didn't post +
anything on my +
Instagram wall. +

I was still 'promoting' +
creative events through my +
Stories, as I usually did +

but when I read through my +
notes for 'Second Perspective' +

I felt incredibly fired up. +

Due to its subject matter, +
I had been putting it off +

since I wasn't sure +
if I could perform it +

without being shut down +
by the opposite sex +

but during that month +
of no new poetry, +

it was like an obsession +
had taken hold. no longer +
was procrastination an option. +

success was and would +
be the only option. +

I had already written +

the sensitive showstopper, +
https://scriptindex.github.io/2018/10/14/perspective-1.html['Perspective 1'] +

but it is only once +
I had performed it +

that a new truth +
was revealed to me. +

I was reaching a new arc +
in my creative career. +

If you were there +

on Thursday 20th December 2018 +

for the first and +
only performance +

of the spectacular sensation +
https://scriptindex.github.io/2018/12/17/second-perspective.html['second perspective'], +

I forgot to mention that +
those words were not mine +

that I had applied +
my creative touch +
with great precision +

so if you've reached this +
far and haven't exploded +
with rage, keep reading... +

I'm not done yet. +

-

I've given you all +
the information you +
require to understand +

why this event holds +
so much importance +
for me, but if you +

really want to know +
why I wrote the poem +

the one you are +
reading right now, +

there is a very +
simple answer +

-

This is a story +
that deserves +
to be told. +

The story you +
deserve to know. +

It will not be +
invalidated or +
silenced +

suppressed, +
or distorted +

by anyone +
or everyone. +

May it be a lesson +
to those who think +
otherwise. +

-

To conclude, I would like +
to personally deliver this +
handwritten letter to its +
rightful recipient... +

...

To https://www.instagram.com/theyoniversecollective[The Yoniverse], +

It is Saturday 23rd November 2019. +

It has been exactly one year +
since I came on your stage +
to recite my poetry. +

three hundred and +
sixty five days later, +

I hope this is the +
learning experience +
you were looking for. +

The Yoniverse, +

It seems you underestimated +
what one South Asian man +
is capable of. +

I hope you will not make +
the same mistake twice. +

I do not expect a +
response, for the +
time has long gone. +

I know you will +
not forget this +

but it doesn't +
matter anymore +

because... +

there is nothing +
left to say. +

it's over +

so I shall leave you +
with the very words +

I said to your founder +
on that fateful evening: +

"I hope I don't take up +
too much time in your +
red book meeting." +

Yours truly, +
https://www.instagram.com/scriptindex/[scriptindex]

_-scriptindex, 23/11/19 sat_