= true source
:hp-tags: poetry
:published-at: 2019-01-26

hello.

---

these two hands +
of mine I offer +
in your name. +

I have been missing +
for far too long +

and the fault +
is only mine. +

it is only natural +
for one's creation +
to search for +
its source, so +

this relationship of +
the soul and its source +
is a perplexing one. +

it shall not conclude +
when I return to the +
dust of the Earth, +

when these countless planets +
and wondrous stars above +
our heads no longer exist, +

when there is nothing +
but you and your will, +

but shall exist until +
you say otherwise. +

to estimate your value +
would be truly disrespectful +

to question your actions +
it would be unjust +

so I ask you this +

Give us your support, +
most benevolent, +
magnificent and +
most forgiving one. +

I ask not for myself +
but for all of creation. +

'Most Beneficent, Most Merciful.' +

this world has not +
been kind to us +

yet we believe in you. +

this life becomes +
unbearable + 

still we believe in you. +

'The Timeless, All-Knowing, +
The Incomparable.' +

my words mean nothing +
in your presence +

but I speak them +
in the hope that +
you will listen. +

'The Infinite, +
The Truth.' +

I am selfish with +
my lowly demands +

and I have no right +
to ask, but the one +
thing I know is that +

you will listen +

someday

_-scriptindex, 26/01/19 sat_ 