= one year later
:hp-tags: poetry
:published-at: 2019-11-23

Before we begin, +
I would like to state the following: +

[This poem has been on my mind for the past year. +
If the matter was resolved, it would not exist. +
I have to stand up for myself, because no one else +
can, or will. In that sense, I have no regrets.] +

This is the longest piece I have ever written. +
It's quite conversational, so you will enjoy it. +

It is best experienced by reading through the +
entire thing, then checking all of the hyperlinks. +

So, you're finally ready. Let us begin. +

---

Friday 23rd November 2018. +

I was heading to the +
Rich Mix in Shoreditch +

to enjoy an evening of +
spoken word and music +

and perform a very +
personal poetry piece. +

This collaboration between +

the South Asian female +
poetry collective, +

https://www.instagram.com/theyoniversecollective[The Yoniverse] and singer-songwriter +
https://www.instagram.com/leokalyan[Leo Kalyan] would "reimagine masculinity +
through a queer and feminist lens" +

in the appropriately titled: +

https://richmix.org.uk/events/the-yoniverse-x-leo-kalyan-present-the-edge/[THE YONIVERSE X LEO KALYAN PRESENT: THE EDGE]

Looking at these https://www.facebook.com/pg/theyoniversecollective/photos/?tab=album&album_id=298107960823996[lovely photos], +
it looks like everything went well.

there's a https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298108187490640/?type=3&theater[few] pictures of https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298109637490495/?type=3&theate[me] +
performing on that https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298110540823738/?type=3&theater[stage], +

some https://www.instagram.com/p/Bqm0lwunQ9A/[nice buns] and +
lots of https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298110407490418/?type=3&theater[happy smiles]. +

-

but this is not +
the full story. +

what if I told you +

there is an +
untold story +

that no one +
will ever know? +

-

the time has come +
to reveal all. +

this is the real +
"learning experience". +

tonight, you will +
learn many things, +

including... +

the incident itself, +
my search for the truth, +
the response I received, +
how it has affected me, +
why this piece exists +
and my final thoughts +
to The Yoniverse. +

I have tried my best +
to tell you how it went. +

There may be some +
discrepancies in terms +
of the ordering, but +

I have tried my best +
to be honest with you. +

I hope you can trust me. +

-

Friday 23rd November 2018. +

I wanted to perform +
a https://scriptindex.github.io/2018/09/11/Women.html[spoken word] piece +
I had https://farm66.static.flickr.com/65535/48596076557_f842c1df74.jpg[memorized] for +
a recent https://www.youtube.com/watch?v=LWjxVYxxkGE[poetry event]. +

I had two things to consider. +

Firstly, there were +
only five open mic +
slots on the night. +

Secondly, I saw https://www.instagram.com/theyoniversecollective[their] +
Instagram post about +
their unique open mic +
policy (now removed) +

which gave priority +
to South Asian +
https://feministoasis.com/inclusive-language-womxn-cis-nonbinary[womxn] 
and queerfolk. +

I had never seen a policy +
like this, so I was sure +
to get there early. +

it was the only thing +
I could really do +

to maximise my chances +
of performing there.

-

on the night, I saw +
the following members +
of The Yoniverse: +

https://www.instagram.com/shaguftakiqbalpoet[Shagufta K Iqbal], +
https://www.instagram.com/shareefaenergy[Shareefa Energy], +
https://www.instagram.com/amanithepoet[Amani Saeed]. +

https://www.instagram.com/salmaelwardany[Salma El-Wardany] was +
also https://www.facebook.com/theyoniversecollective/photos/a.298107960823996/298111400823652/?type=3&theater[there] but I didn't +
see her on the night. +

As I asked around, +

I realised Amani +
was signing up +
the open micers +

so I went up to her +
and she wrote my +
name down. +

-

The event itself was +
actually pretty good. 

https://www.instagram.com/leokalyan[Leo Kalyan] discussed +
his creative process +

and beautifully sang +
his latest EP: https://www.youtube.com/watch?v=s4KcLu9CNdo[the edge], +

https://www.instagram.com/shareefaenergy[Shareefa Energy] carefully +
recited her soul-soothing, +
tongue-twisting poetry +

and https://www.instagram.com/raheemmir[Raheem Mir] performed +
some barrier-breaking, +
gender-bending https://kathadance.org/about-2/what-is-kathak/[Kathak]. +

I thoroughly enjoyed +
myself and was looking +
forward to coming back +

the next time.

-

It was time. +

My name was called. +

The time had come +
to perform the piece +

I had memorized +
off by heart. +

https://scriptindex.github.io/2018/09/11/Women.html['Women.'] +

-

things were alright +
at the beginning +

but as the piece +
drew to a close, +

there was +

a growing +
commotion +
of sorts. +

I could hear +

Shagufta, who +
was talking to +
someone near her. +

"...this can't go on..." +

it took a few seconds +

but when I realised +

"it's a tricky +
situation, and-" +

I stopped. +

pure silence. +

-

there was this one +
brown girl. the one +
with the colourful +

jacket. her energy +
was a bit strange +
that evening. +

she seemed like +
she was angry +
in general +

and expressed +
her distaste +
quite vocally +

when she shouted: +

"Women are not your playthings!" +

what? +

to this day, +
I have no clue +
what she meant +

but that was +
just the start. +

there was also +
this white girl +

standing behind a table +
at the back of the room. +

I don't know who she is +

but she knows who she is. +

she was very +
offended by +

something +
I had said. +

she also chose +
to be vocal. +

-

I don't remember +
the exact words +

but Amani walked +
towards me, saying +

they didn't know +
it was "that +
kind of piece" +

so she asked me +
to give back the mic. +

-

in my entire career +
as a spoken word artist +

that was the first time +
I had been asked to +
give back the mic. +

when you don't +
know why, well, +

I'm sure you can +

imagine how it feels... +

-

https://www.instagram.com/shaguftakiqbalpoet[Shagufta] said they +
(as in, the team) +
were waiting +

to see if the +
piece would +
change +

and it didn't. +

I wondered how +
things had come +
to this. +

why I decided +
to perform +
that piece. +

why I came +
to this event. +

just why. +

-

right before +
I was about +
to give the +
mic back

I took the +
opportunity +
to say that +

I was sorry +

if I hurt +
anyone's +
feelings. +

in retrospect, +

I should never +
have said sorry. +

it's pretty simple. +

when you offend someone, +
especially liberals, +

your apology +
is meaningless. +

it's damage control +
in their eyes. +

they want more +
than just an +
apology... +

they want +
your blood, +
your career, +
your social +
standing +

destroyed. +

they will do +
whatever they can +
to take you down. +

I had read about +
this countless +
times, but this +

was the first time +
I understood it +

and I vowed to learn +
from that experience +

so it wouldn't +
happen again. +

-

there is one +
silver lining +
to this drama. +

as I was about +
to leave the stage, +

https://www.instagram.com/leokalyan[Leo Kalyan] had +
something to say +

so he came on stage +
to present his thoughts. +

I believe he placed +
emphasis on how, +
sometimes, it's +

important to let +
ourselves feel +
uncomfortable. +

I was still +
in shock, so +

I can't recall +
the finer details +

but over time, +

he was able to +
calm the crowd +

and direct their +
thoughts to more +
wholesome ones. +

Cheers, Leo. +

-

there was one +
last person on +
the open mic +

so once they +
had finished, +

it was decided +
that there would +
be a discussion +

of some kind +

about what +
just happened. +

it would be... +

"a learning experience." +

-

now that I had +
derailed the +
entire evening +

there was an +
unscripted and +

https://twitter.com/DimplePau/status/1066100076949450752["passionate discussion] +
on free speech."

there was some talk +
about culture and +
socialization. +

one womxn said +
"it can take time +
to unlearn things" +

and more womxn +
expressed their +
views on how the +

situation could +
have been handled. +

everything seemed +
to be going well. +

the audience was +
responsive enough. +

it was an engaging +
and interesting +
discussion. +

damage control +
was in full +
effect +

and it was fine. +

-

as I said earlier, +
https://www.instagram.com/salmaelwardany[Salma] was present. +

the voice sounded +
similar and I think +
she's the one who, +

when asked for her +
thoughts, said +
"I hate men..." +

but that was quite +
dehumanizing and +
could have been +
handled better. +

could have been +
someone else, +
though...

who knows. +

-

at some point, +

white girl decided +
she was not satisfied. +

she could not +
comprehend what +
was going on +

so she asked Leo and +
Amani if she could ask +
me a question. +

I think she asked me +
why I wrote the piece +
or what I was thinking +
when I wrote it. +

can you imagine, +

having literally +
everyone in the +
entire room +

roughly seventy +
five people or so +

turning to look +
directly at you +

expecting a response +

while you are still +
in a state of shock? +

I don't even want +
to think about it. +

fortunately, I was +
still somewhat sane +
at that point, +

saying something about +
my personal experience +
and how I'm still in a +

state of shock right now +
so I can't think properly. +

all I would like to say, is +

thanks for that, +
white girl. +

no, really. +

I hope I never see you +
again in my entire life. +

-

over time, +

it became apparent +
that many womxn were +
annoyed that they +

didn't hear +
the full piece. +

perhaps they could +
not confirm their +
suspicions, or +

properly judge it +
without hearing it +
in its entirety. +

I believe the +
best reasoning +
came from one +
womxn, +

who claimed that +

I could flip the +
entire piece on +

its head in the +
last few lines... +

-> https://scriptindex.github.io/2019/11/23/one-year-later-2.html[(continued in part 2)]

_-scriptindex, 23/11/19 sat_