
= CREATE NEW POST ON 23/11 oyl
:hp-tags: poetry
:published-at: 2019-11-21 NEW POST -23

Before the show begins, +
I would like to state the following: +

[This poem has been on my mind for the past year. +
If the matter was resolved, it would not exist. +
I have to stand up for myself, because no one else +
can, or will. In that sense, I have no regrets.] +

It is best experienced by reading through the +
entire thing, then checking all of the hyperlinks. +

So, you're finally ready. Let us begin. +

---

Friday 23rd November 2018. +

I had a few things to 


though tonight +

I was heading to the +
https://richmix.org.uk/events/the-yoniverse-x-leo-kalyan-present-the-edge/[Rich Mix in Shoreditch] +

to perform a https://scriptindex.github.io/2018/09/11/Women.html[spoken word piece] +
I had memorised not long ago +
for https://www.youtube.com/watch?v=LWjxVYxxkGE[another poetry event] +

to a demographic of

Looking at these https://www.facebook.com/pg/theyoniversecollective/photos/?tab=album&album_id=298107960823996[lovely photos], +
it looks like everything went well.

there's a [few] of [me] +
on that [stage]



What if I told you +
things weren't as +
cheerful as they might seeM?


A man has got to do +
what a man has gotta do. +


, to man up.

F



_-scriptindex, 23/11/19 sat_




