= blog poem draft
:hp-tags: poetry
:published-at: [2019-12-29]

https://www.youtube.com/watch?v=NIDZbPkNIgI[~Interrupted] 
https://www.youtube.com/watch?v=6Pi9xgOXvTs[by] 
https://www.youtube.com/watch?v=vPu7AL2fSyk[Fireworks.]

---

a few days ago, +
I realised something +

so incredibly important. +

I can't ignore it, +
I won't deny it +

so, let's be honest. +

someone has to say it. +

-

it's been a month since +
I made myself clear, but +

you haven't responded, yet. +

you're a nice girl +

I'm glad we met +
over the years +

and spent some +
moments together. +

in my spare time, +

I've made it clear +
what you mean to me +

from my first poem +
to my last, and all +
the ones in between +

but now, +

I can't do this +
to myself anymore. +

I can't ignore +
my friends' +
valuable advice. +

I can't defend +
you anymore. +

-

I have finally reached +
my breaking point. +

it's unhealthy to +
go on like this +

so I'm taking a break. +

I don't know +
how long, but +

I need to heal +
these aspects +
of my life +

I need to learn +
how I let things +
reach this point. +

I want to stop this +

before the cycle +
repeats itself +

to repeat itself. +

-

I have realised +

we just don't share +
the connection +

I thought we had. +

I have realised +

I'm just another boy +
on your list, +

in your inbox, +

in your thoughts +

on your mind, +

not in your heart. +

-

to reach this point +
I had to create +

an exception +

for you, but +

I've been careful to +
not let myself get too +

emotionally involved. +

the only truth is +

I don't love you. +

I've already expressed +
my feelings in words +

for your ears, +
your eyes, +

your heart +

and your +
lovely smile. +

anything else +
doesn't matter. +

-

at this point +
in my life +

I deserve someone +

who knows how +
to respect a man, +

who will receive +
this special gift +

of mine with +
open arms +

who will stand by me  +
when times are tough, +

who can accept me +
for who I really am +

who wants to +
spend the rest of +
her life with me. +

-

right now, +

we're just two different people +
living two different lives. +

I don't think +
anything will +
change +

but things +
will change +

they always do. +

if you want to keep +
acting the same way, +

that's up to you +

but you should +
know by now... +

if you play around +

with a gentleman +
of my calibre, +

you will lose out +
in more ways +
than one. +

-

you have a +
great purpose +
in my life. +

you had the power +
to direct me closer +

to my heart, +

you were my +
creative influence +

shaping the +
lovely waves of +
my poetry. +

some may call you +
my stepping stone, +

and I truly agree +

for you see, +
sweetheart +

these poetry pieces +
exist for a reason. +

if you weren't there +
to inspire them, +

if I wasn't there +
to write them... +

-

perhaps you will +
understand when +
you are older +

or perhaps +

one day, you will explore +
your past and wonder why +

he came into your life +
only to leave before +

his time had come. +

all I will say, is +

you can try +

I won't stop you +

but, +

for my sake, +

you don't need +
to worry so much. +

_-scriptindex, 29/12/19 _

https://scriptindex.github.io/2019/11/29/to-you.html

from the https://scriptindex.github.io/2018/08/29/Lover.html[first] to the https://scriptindex.github.io/2019/11/29/to-you.html[last] and +
https://scriptindex.github.io/2018/09/11/Women.html[a few] of https://scriptindex.github.io/2018/09/29/Revelation.html[the ones] in https://scriptindex.github.io/2019/09/08/body-language.html[between], +