= secrets
:hp-tags: poetry
:published-at: [2020-01-31]

a retrospective update with some corrections.

---

in December 2019, +
I realised something +

so incredibly important. +

I can’t ignore it, +
I won’t deny it +

so, I’ll be honest. +

someone has to say it. +

-

it's been two months since +
https://scriptindex.github.io/2019/11/29/to-you.html[I made myself clear], but +

you haven't responded yet. +

you're a nice girl, +

I'm glad we met +
over the years +

and spent some +
moments together. +

in my spare time, +

I made it clear +
what you meant to me +

from my https://scriptindex.github.io/2018/08/21/absence.html[first] poem +
https://scriptindex.github.io/2018/08/29/Lover.html[to] my
https://scriptindex.github.io/2019/12/31/prayer.html[last] and https://scriptindex.github.io/2019/08/27/promise.html[all] +
the https://scriptindex.github.io/2018/09/11/Women.html[ones] in https://scriptindex.github.io/2019/09/08/body-language.html[between] +

but now, +

I can't do this +
to myself anymore. +

I can’t ignore +
my friends' +
valuable advice. +

I can’t defend +
you anymore. +

-

I had finally reached +
my breaking point. +

it was unhealthy to +
keep going on like this, +

so https://scriptindex.github.io/2018/09/10/weeks.html[I’ve taken a break]. +

I don't know +
how long, but +

I need to heal +
these aspects +
of my life. +

I need to learn +
how I let things +
reach this point. +

I will stop this +

before the cycle +
repeats itself +

to repeat itself +

-

I have realised +

we just don't share +
the connection +

I thought we had. +

I have realised +

I'm just another boy +
on your list +

in your inbox, +

in your thoughts +

on your mind, +

not in your heart. +

-

https://scriptindex.github.io/2018/09/06/failure.html[to reach this point] +
I had to create +

an exception +

for you, but +

I was careful +
not to get too +

emotionally involved. +

the only truth is +

I don't love you. +

I've already expressed +
my feelings in words +

for your ears +
your eyes, +

your heart +

and your +
lovely smile +

anything else +
doesn't matter. +

-

at this point +
in my life, +

I deserve someone +

who knows how +
to respect a man, +

who will receive +
this special gift +

of mine with open arms +

who shall stand by me +
when times are tough, +

who can accept me +
for who I really am +

who wants to +
spend the rest of +
her life with me. +

-

right now, +

we're just two +
different people +

living two +
different lives. +

I don't think +
anything will +
change +

but things +
will change, +

they always do. +

-

if you want to keep +
acting the same way, +

that's up to you +

but you should +
know by now -  +

if you play around +

with a gentleman +
of my calibre, +

you will lose out +
in more ways +
than one. +

-

you had a +
https://scriptindex.github.io/2018/09/29/Revelation.html[great purpose] +
in my life. +

you had the power +
to direct me closer +

to my heart, +

you were my +
creative influence, +

shaping the +
lovely waves of +
my poetry. +

some have called you +
my stepping stone, +

and I truly agree +

for you see, +
sweetheart +

these poetry pieces +
exist for a reason. +

if you weren't there +
to inspire them, +

if I wasn't there +
to write them... +

-

perhaps you will +
understand when +
you are older +

or perhaps +

one day, you will +
explore your past +

and wonder why +

he came into your life +
only to leave before +

his time had come. +

all I will say, is +

https://scriptindex.github.io/2019/08/18/The-Ideal-Situation.html[you can try], +

I won't stop you +

but, +

for my sake +

you don't need +
https://scriptindex.github.io/2019/08/22/okay.html[worry] about me. +

_-scriptindex, 31/01/20 fri_